from slack_sdk.web.async_client import AsyncWebClient
from slack_sdk.errors import SlackApiError
from core.config import get_settings
from core.logging import get_logger
from models.meeting import MeetingResult, UtteranceType

logger = get_logger(__name__)
settings = get_settings()


def _get_client() -> AsyncWebClient:
    return AsyncWebClient(token=settings.slack_bot_token)


def _build_digest(result: MeetingResult) -> list[dict]:
    """Build Slack Block Kit message for meeting digest."""
    blocks = [
        {"type": "header", "text": {"type": "plain_text", "text": f"Meeting recap: {result.title}"}},
        {"type": "divider"},
    ]

    if result.summary:
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": result.summary}
        })
        blocks.append({"type": "divider"})

    if result.decisions:
        decision_lines = "\n".join(f"• {d.text}" for d in result.decisions[:5])
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Decisions made*\n{decision_lines}"}
        })

    if result.tasks:
        task_lines = "\n".join(
            f"• {t.title}" + (f" → *{t.owner}*" if t.owner else "") + (f" _(by {t.deadline})_" if t.deadline else "")
            for t in result.tasks[:8]
        )
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Action items*\n{task_lines}"}
        })

    if result.open_questions:
        oq_lines = "\n".join(f"• {q.text}" for q in result.open_questions[:4])
        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": f"*Open questions*\n{oq_lines}"}
        })

    blocks.append({
        "type": "context",
        "elements": [{"type": "mrkdwn", "text": f"Generated by MeetMind • {len(result.tasks)} tasks created"}]
    })

    return blocks


async def send_digest(result: MeetingResult, channel: str = None) -> bool:
    if not settings.slack_bot_token:
        logger.warning("Slack token not set — skipping")
        return False

    slack = _get_client()
    target = channel or settings.slack_default_channel

    try:
        await slack.chat_postMessage(
            channel=target,
            blocks=_build_digest(result),
            text=f"Meeting recap: {result.title}",  # fallback for notifications
        )
        logger.info(f"Slack digest sent to {target}")
        return True
    except SlackApiError as e:
        logger.error(f"Slack error: {e.response['error']}")
        return False
